services:
  fiap.filecut.upload.api:
    container_name: upload-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      
      - OPENID_AUTHORITY=http://keycloak:8080/realms/sample
      - OPENID_AUDIENCE=admin-cli

      - SMTP_SERVER=fakemail
      - SMTP_PORT=1025
      - SMTP_USERNAME=fakemail-noreplay@test.com

      - RABBITMQ_CONNECTION_STRING=amqp://admin:admin@rabbitmq:5672
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - local_network

  fakemail:
    container_name: fakemail
    ports:
      - "1025:1025"
      - "1080:1080" # portal aqui http://localhost:1080
    networks:
      - local_network

  keycloak:
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KC_HOSTNAME=keycloak
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./libs/Fiap.FileCut/sample-realm.json:/opt/keycloak/data/import/sample-realm.json
    ports:
      # Lembrar de configurar o alias no arquivo hosts apontando keycloak para localhost
      - "8080:8080" # portal aqui http://keycloak:8080
    networks:
      - local_network

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # portal aqui http://localhost:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  keycloak_data: